baseURL = "https://takiguchi-yu.github.io/hugoQuickstart/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ananke"

[params]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://facebook.com/Example"
  twitter = "https://twitter.com/Example"
  instagram = "https://instagram.com/Example"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2